### ISSUE TITLE
Fatal error: Uncaught RuntimeException: No PSR-7 library detected

### ISSUE THREAD

**Issue by mambax7** [kevinsmith/no-framework#12]
I wanted to try it on my WampServer on PHP 7.4.4, but I got this:
`Fatal error: Uncaught RuntimeException: No PSR-7 library detected in C:\wamp64\www\no-framework\vendor\middlewares\utils\src\Factory.php:70 

Stack trace:
#0 C:\wamp64\www\no-framework\vendor\middlewares\utils\src\Factory.php(96): Middlewares\Utils\Factory::getFactory('response') 
#1 C:\wamp64\www\no-framework\vendor\middlewares\fast-route\src\FastRoute.php(35): Middlewares\Utils\Factory::getResponseFactory() 
#2 C:\wamp64\www\no-framework\public\index.php(42): Middlewares\FastRoute->__construct(Object(FastRoute\Dispatcher\GroupCountBased)) 
#3 {main} thrown in C:\wamp64\www\no-framework\vendor\middlewares\utils\src\Factory.php on line 70`

Am I doing something wrong?

**Comment by kevinsmith** [comment]
Did you install the composer dependencies?

**Comment by mambax7** [comment]
Yes, of course.

**Comment by bsoliveira** [comment]
Apparently it installs the version of zendframework/zend-diactoros 1.3, looking in the respective vendor folder I didn't find the ResponseFactory.

**Comment by bsoliveira** [comment]
In composer replace zendframework/zend-diactoros with laminas/laminas-diactoros. 

In the pullic/index file replace the lines:

12 - use Zend\Diactoros\Response -> Laminas\Diactoros\Response
13 - use Zend\Diactoros\ServerRequestFactory -> Laminas\Diactoros\ServerRequestFactory

That way it worked here.

**Comment by mambax7** [comment]
Thanks for the help! 
The first page works now. The second one, Hello, gives me: "The requested URL was not found on this server."

**Comment by bsoliveira** [comment]
Since you are using WampServer, I believe it uses Apache as a web server. Try creating the file "/public/.htaccess" with the following content:

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]

**Comment by mambax7** [comment]
Perfect! Now it works! 
Thank you so much for your help!

**Comment by kevinsmith** [comment]
Thanks for bringing this to light, @mambax7! Looks like I just needed to replace those abandoned dependencies and upgrade everything to keep up to date. Done!
