### ISSUE TITLE
Support for PHP 7.2?

### ISSUE THREAD

**Issue by stefanos82** [kevinsmith/no-framework#3]
I have tried your code with PHP 7.2.9-1 on my Debian testing 64-bit machine and get a white screen.

I have also downloaded this code to compare it with mine in case of some typos or missing code snippets and they are identical.

Is there anything you could advice me to check @kevinsmith ?

**Comment by syntaxseed** [comment]
Works for me on 7.2 (PHP 7.2.11-4+ubuntu16.04.1).

What I did:

- updated the **composer.json** to require 7.2.*.
- ran **composer update**.
- visit the **/hello** route. Works!

**Comment by kevinsmith** [comment]
@stefanos82 Are you loading `http://localhost:8080` or `http://localhost:8080/hello`? The first part of the tutorial goes with `http://localhost:8080`, but by the end, it's `/hello`.

**Comment by stefanos82** [comment]
It doesn't matter; it still throws an error:

First with `https://locahost:8000/`:
```
stefanos@debian:~/code/no-framework$ php -S localhost:8000 -t public/
PHP 7.2.9-1 Development Server started at Tue Nov 13 07:48:41 2018
Listening on http://localhost:8000
Document root is /home/stefanos/code/no-framework/public
Press Ctrl-C to quit.
[Tue Nov 13 07:48:50 2018] PHP Fatal error:  Uncaught Error: Class 'Zend\Diactoros\Response\SapiEmitter' not found in /home/stefanos/code/no-framework/public/index.php:43
Stack trace:
#0 {main}
  thrown in /home/stefanos/code/no-framework/public/index.php on line 43
[Tue Nov 13 07:48:50 2018] ::1:48646 [500]: / - Uncaught Error: Class 'Zend\Diactoros\Response\SapiEmitter' not found in /home/stefanos/code/no-framework/public/index.php:43
Stack trace:
#0 {main}
  thrown in /home/stefanos/code/no-framework/public/index.php on line 43
[Tue Nov 13 07:48:50 2018] ::1:48648 [404]: /favicon.ico - No such file or directory
[Tue Nov 13 07:48:50 2018] ::1:48650 [404]: /favicon.ico - No such file or directory
```
Second case with `https://localhost:8000/hello`:
```
stefanos@debian:~/code/no-framework$ php -S localhost:8000 -t public/
PHP 7.2.9-1 Development Server started at Tue Nov 13 07:52:37 2018
Listening on http://localhost:8000
Document root is /home/stefanos/code/no-framework/public
Press Ctrl-C to quit.
[Tue Nov 13 07:52:44 2018] PHP Fatal error:  Uncaught Error: Class 'Zend\Diactoros\Response\SapiEmitter' not found in /home/stefanos/code/no-framework/public/index.php:43
Stack trace:
#0 {main}
  thrown in /home/stefanos/code/no-framework/public/index.php on line 43
[Tue Nov 13 07:52:44 2018] ::1:48728 [500]: /hello - Uncaught Error: Class 'Zend\Diactoros\Response\SapiEmitter' not found in /home/stefanos/code/no-framework/public/index.php:43
Stack trace:
#0 {main}
  thrown in /home/stefanos/code/no-framework/public/index.php on line 43
```

**Comment by syntaxseed** [comment]
Did you run 'composer update'?
Is that missing package installed?

**Comment by stefanos82** [comment]
@syntaxseed Everything is installed as required.

**Comment by kevinsmith** [comment]
@stefanos82 Just for my sake, could you delete the `vendor` dir and run `composer install` again? Something seems to be missing, and that command should take care of it.

**Comment by stefanos82** [comment]
@kevinsmith that's what I did, plus I copied your own composer.json so I can match the necessary versions except PHP; I updated it to match my 7.2.x version and now works as expected.

So, in order to save others from facing the same issue, here's my own `composer.json`:
```json
{
    "name": "stefanos/no-framework",
    "description": "An example of a modern PHP application bootstrapped without a framework.",
    "type": "project",
    "require": {
        "php": "7.2.*",
        "php-di/php-di": "^6.0",
        "relay/relay": "2.x@dev",
        "zendframework/zend-diactoros": "^1.7",
        "middlewares/fast-route": "^1.0",
        "middlewares/request-handler": "^1.1"
    },
    "autoload": {
        "psr-4": {
            "ExampleApp\\": "src/"
        }
    }
}
```

**Comment by kevinsmith** [comment]
Glad to see you found a solution, @stefanos82!

**Comment by stefanos82** [comment]
@kevinsmith any plans to write a book about such topic?

I'm sure others would love to have a fully functional project that proves us there's no need to depend on any framework anymore, thanks to Composer and Packagist.

**Comment by kevinsmith** [comment]
Perhaps in the future, but I certainly plan on writing more blog posts that cover this and other foundational topics. It seems to me there's not much good, accessible educational content in that space.

I've also considered just open sourcing one of my own side projects from the start and building it completely out in the open for anyone who wants to peek in. That way it's a real project with real concerns, not something conjured up for the sake of a tutorial.

**Comment by stefanos82** [comment]
I'm interested in this 100%.

Let me know when you release it.

Keep up the good work! :+1:

**Comment by kevinsmith** [comment]
Thanks @stefanos82!
