### ISSUE TITLE
Route middlewares?

### ISSUE THREAD

**Issue by lautiamkok** [kevinsmith/no-framework#6]
How do we add route middlewares to a route? For example:

```
$routes = simpleDispatcher(function (RouteCollector $r) {
    $r->get('/hello', HelloWorld::class);
});
```

And we want to add an authentication midleware or more before `HelloWorld` is called:

`$r->get('/hello', middleware1, middleware2, HelloWorld::class);`

Is this something can be done in PHP or PSR-15?

**Comment by kevinsmith** [comment]
While I believe route middleware is available in some PHP routing systems, it's not something I generally recommend and it's not a feature of the routing system used here.
