### ISSUE TITLE
Copycat found

### ISSUE THREAD

**Issue by r0max** [kevinsmith/no-framework#7]
Hi Kevin, I was reading your article and the code, very good stuff! By coincidence, I stumbled on a copied version of your article on another site, which has been modified only the slightest. It is here: https://medium.com/@mena.meseha/write-modern-php-code-without-using-a-framework-6ff54bc2b6d6. Just to let you know, didn't see any other ways of contacting you.

**Comment by kevinsmith** [comment]
Wow! What a shameless copy. Thank you SO MUCH for bringing it to my attention. I just submitted a takedown notice to Medium, so hopefully they'll act on it soon.
