### ISSUE TITLE
Handler errors

### ISSUE THREAD

**Issue by bsoliveira** [kevinsmith/no-framework#8]
I loved your tutorial, for us who want independence in our projects this is the way. I am now studying ways to deal with errors and exceptions. Could you please give me a hint on how to implement these treatments in your project?

**Comment by kevinsmith** [comment]
Sure @bsoliveira, I have a couple of thoughts. First, I'd recommend reserving exceptions for truly exceptional circumstances. Consider that if you use exceptions for normal errors—like if a new user tries to register an account using an email address that already exists in the system or when the system requests a non-existent record from the database—then the exception is actually a non-obvious part of your class/method's API. You're expecting the caller to know which exceptions might be thrown by your code (or by the code your code is calling). Also, exceptions have a fail-on-first-error behavior. What if you want to signal to the caller that several error conditions have been triggered?

In situations where a particular method could have several different normal error conditions (especially if it can have more than one at a time), I recommend using a handler to give the caller control over how to deal with those errors. https://kevinsmith.io/a-better-way-to-handle-validation-errors

I'd also highlight how important it is to handle errors in the right _place_ in your system. https://kevinsmith.io/sanitize-your-inputs
